# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Grupo sobre SEO
email: facidsi2016.1@gmail.com
copyright_name: "Grupo sobre SEO"
firstname: Grupo
lastname: SEO
my_location: Teresina, Piauí

avatar: https://avatars1.githubusercontent.com/u/38007515?s=400&u=db02e130818c85ff69b15e544620a54a685cf367&v=4

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://facidsiatividades.github.io/"

description: >- # this means to ignore newlines until "baseurl:"
  Blog criado com técnicas de SEO como pratica do trabalho sobre SEO - Search Engine Optimization

keywords: SEO, Marketing Digital, Mercado Digital, Publicidade, Sitemap, Google Analytics, Markdown, Marketing, Jekyll, Teresina, Piauí, Brasil

github_username: facidsiatividades
facebook_username: 
linkedin_username: 
google_plus_username: 
email_username: facidsi2016.1@gmail.com
disqus_shortname: facidsiatividades

curriculo_doc: 

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-117205875-1



timezone: America/Fortaleza

# Build settings
markdown: kramdown
theme: minima
paginate: 10
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
